# Generated by Django 3.2 on 2021-04-17 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sort',
            old_name='sort_name',
            new_name='name',
        ),
    ]
