# Generated by Django 3.2 on 2021-04-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_sort_name_sort_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
